@url = https://localhost:5001/api
@username = bob
@password = password

### getusers
GET {{url}}/users HTTP/1.1

### login
# @name loginResponse
POST {{url}}/account/login HTTP/1.1
Content-Type: application/json

{
    "username":"{{username}}",
    "password":"{{password}}"

}

###
@token = {{loginResponse.response.body.token}}
###getuser
GET {{url}}/users/2 HTTP/1.1
Authorization: Bearer {{token}} 

